### ISSUE TITLE
Usage of deprecated features - extension will stop working with HA 2025.1

### ISSUE THREAD

**Issue by d4g** [GeorgeSG/philips_airpurifier_http#15]
On startup, the extension produces 2 warnings, stating that this will not work anymore with HA Core 2025.1

> Logger: homeassistant.components.fan
> Source: helpers/deprecation.py:197
> integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
> First occurred: June 13, 2024 at 01:20:19 (4 occurrences)
> Last logged: June 13, 2024 at 01:20:19
> 
>     SUPPORT_SET_SPEED was used from philips_airpurifier_http, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please report it to the author of the 'philips_airpurifier_http' custom integration
>     SUPPORT_PRESET_MODE was used from philips_airpurifier_http, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please report it to the author of the 'philips_airpurifier_http' custom integration

> Logger: homeassistant.helpers.entity
> Source: helpers/entity.py:1628
> First occurred: June 13, 2024 at 01:20:19 (1 occurrences)
> Last logged: June 13, 2024 at 01:20:19
> 
> Entity fan.philips_airpurifier (<class 'custom_components.philips_airpurifier_http.fan.PhilipsAirPurifierFan'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|PRESET_MODE: 9>, please create a bug report at https://github.com/GeorgeSG/philips-airpurifier/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by GeorgeSG** [comment]
Released version 1.5.0. This should fix those warnings

**Comment by stefan-girlich** [comment]
Hi @GeorgeSG , when validating my config, I'm getting this error in the Home Assistant web UI:

`Platform error 'fan' from integration 'philips_airpurifier_http' - cannot import name 'SUPPORT_SET_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
`

I manually downloaded v1.5.0, but the contained manifest.json still contains `  "version": "1.4.2"` - not sure if this means that the actual code is outdated or if the version is just not bumped in the release on GitHub

_Update:_
manifest.json version issue seems unrelated. Error message disappeared after a fresh install
